# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OscillGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1254, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(10, 558, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_settings_header = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.image_settings_header.setFont(font)
        self.image_settings_header.setObjectName("image_settings_header")
        self.verticalLayout_3.addWidget(self.image_settings_header)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.imaging_time = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.imaging_time.setProperty("value", 48.0)
        self.imaging_time.setObjectName("imaging_time")
        self.gridLayout.addWidget(self.imaging_time, 2, 3, 1, 1)
        self.background_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.background_group_box.setObjectName("background_group_box")
        self.dark_radio_button = QtWidgets.QRadioButton(self.background_group_box)
        self.dark_radio_button.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.dark_radio_button.setObjectName("dark_radio_button")
        self.light_radio_button = QtWidgets.QRadioButton(self.background_group_box)
        self.light_radio_button.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.light_radio_button.setObjectName("light_radio_button")
        self.gridLayout.addWidget(self.background_group_box, 1, 0, 3, 2)
        self.submit_settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_settings_button.setObjectName("submit_settings_button")
        self.gridLayout.addWidget(self.submit_settings_button, 3, 2, 1, 1)
        self.length_conversion_label = QtWidgets.QLabel(self.centralwidget)
        self.length_conversion_label.setObjectName("length_conversion_label")
        self.gridLayout.addWidget(self.length_conversion_label, 1, 2, 1, 1)
        self.folder_label = QtWidgets.QLabel(self.centralwidget)
        self.folder_label.setObjectName("folder_label")
        self.gridLayout.addWidget(self.folder_label, 0, 0, 1, 1)
        self.imaging_time_units = QtWidgets.QLabel(self.centralwidget)
        self.imaging_time_units.setObjectName("imaging_time_units")
        self.gridLayout.addWidget(self.imaging_time_units, 2, 4, 1, 1)
        self.length_conversion = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.length_conversion.setMaximum(9999.99)
        self.length_conversion.setProperty("value", 450.0)
        self.length_conversion.setObjectName("length_conversion")
        self.gridLayout.addWidget(self.length_conversion, 1, 3, 1, 1)
        self.length_conversion_units = QtWidgets.QLabel(self.centralwidget)
        self.length_conversion_units.setObjectName("length_conversion_units")
        self.gridLayout.addWidget(self.length_conversion_units, 1, 4, 1, 1)
        self.imaging_time_label = QtWidgets.QLabel(self.centralwidget)
        self.imaging_time_label.setObjectName("imaging_time_label")
        self.gridLayout.addWidget(self.imaging_time_label, 2, 2, 1, 1)
        self.image_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.image_folder.setObjectName("image_folder")
        self.gridLayout.addWidget(self.image_folder, 0, 1, 1, 3)
        self.image_folder_button = QtWidgets.QToolButton(self.centralwidget)
        self.image_folder_button.setObjectName("image_folder_button")
        self.gridLayout.addWidget(self.image_folder_button, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(268, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setObjectName("filename")
        self.gridLayout_4.addWidget(self.filename, 1, 1, 1, 1)
        self.save_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.save_folder.setObjectName("save_folder")
        self.gridLayout_4.addWidget(self.save_folder, 2, 1, 1, 1)
        self.save_folder_label = QtWidgets.QLabel(self.centralwidget)
        self.save_folder_label.setObjectName("save_folder_label")
        self.gridLayout_4.addWidget(self.save_folder_label, 2, 0, 1, 1)
        self.filename_label = QtWidgets.QLabel(self.centralwidget)
        self.filename_label.setObjectName("filename_label")
        self.gridLayout_4.addWidget(self.filename_label, 1, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.gridLayout_4.addWidget(self.save_button, 3, 1, 1, 1)
        self.save_results_header = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_results_header.setFont(font)
        self.save_results_header.setObjectName("save_results_header")
        self.gridLayout_4.addWidget(self.save_results_header, 0, 0, 1, 3)
        self.save_folder_button = QtWidgets.QToolButton(self.centralwidget)
        self.save_folder_button.setObjectName("save_folder_button")
        self.gridLayout_4.addWidget(self.save_folder_button, 2, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(258, 278, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_10.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        spacerItem3 = QtWidgets.QSpacerItem(11, 558, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.crop_settings_header = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.crop_settings_header.setFont(font)
        self.crop_settings_header.setObjectName("crop_settings_header")
        self.verticalLayout_2.addWidget(self.crop_settings_header)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.full_im_frame = QtWidgets.QFrame(self.centralwidget)
        self.full_im_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.full_im_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.full_im_frame.setObjectName("full_im_frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.full_im_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -1, 301, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.full_im_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.full_im_layout.setContentsMargins(0, 0, 0, 0)
        self.full_im_layout.setObjectName("full_im_layout")
        self.full_im = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.full_im.sizePolicy().hasHeightForWidth())
        self.full_im.setSizePolicy(sizePolicy)
        self.full_im.setObjectName("full_im")
        self.full_im_layout.addWidget(self.full_im)
        self.gridLayout_3.addWidget(self.full_im_frame, 0, 0, 1, 1)
        self.COM_rows = QtWidgets.QSlider(self.centralwidget)
        self.COM_rows.setOrientation(QtCore.Qt.Vertical)
        self.COM_rows.setInvertedAppearance(True)
        self.COM_rows.setObjectName("COM_rows")
        self.gridLayout_3.addWidget(self.COM_rows, 0, 1, 1, 1)
        self.COM_columns = QtWidgets.QSlider(self.centralwidget)
        self.COM_columns.setOrientation(QtCore.Qt.Horizontal)
        self.COM_columns.setObjectName("COM_columns")
        self.gridLayout_3.addWidget(self.COM_columns, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.cropping_note_label = QtWidgets.QLabel(self.centralwidget)
        self.cropping_note_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cropping_note_label.setObjectName("cropping_note_label")
        self.verticalLayout_2.addWidget(self.cropping_note_label)
        spacerItem4 = QtWidgets.QSpacerItem(328, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.set_crop_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_crop_button.setObjectName("set_crop_button")
        self.gridLayout_2.addWidget(self.set_crop_button, 2, 0, 1, 2)
        self.ideal_crop_label = QtWidgets.QLabel(self.centralwidget)
        self.ideal_crop_label.setObjectName("ideal_crop_label")
        self.gridLayout_2.addWidget(self.ideal_crop_label, 0, 0, 1, 1)
        self.ideal_crop = QtWidgets.QSpinBox(self.centralwidget)
        self.ideal_crop.setMaximum(999)
        self.ideal_crop.setProperty("value", 175)
        self.ideal_crop.setObjectName("ideal_crop")
        self.gridLayout_2.addWidget(self.ideal_crop, 1, 0, 1, 1)
        self.ideal_crop_units = QtWidgets.QLabel(self.centralwidget)
        self.ideal_crop_units.setObjectName("ideal_crop_units")
        self.gridLayout_2.addWidget(self.ideal_crop_units, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(68, 98, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem5, 1, 1, 1, 1)
        self.cropped_im_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cropped_im_frame.sizePolicy().hasHeightForWidth())
        self.cropped_im_frame.setSizePolicy(sizePolicy)
        self.cropped_im_frame.setAutoFillBackground(False)
        self.cropped_im_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.cropped_im_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cropped_im_frame.setObjectName("cropped_im_frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.cropped_im_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, -1, 241, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.cropped_im_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.cropped_im_layout.setContentsMargins(0, 0, 0, 0)
        self.cropped_im_layout.setObjectName("cropped_im_layout")
        self.cropped_im = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cropped_im.sizePolicy().hasHeightForWidth())
        self.cropped_im.setSizePolicy(sizePolicy)
        self.cropped_im.setObjectName("cropped_im")
        self.cropped_im_layout.addWidget(self.cropped_im)
        self.gridLayout_5.addWidget(self.cropped_im_frame, 0, 0, 2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(328, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(10, 558, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.segmentation_settings_header = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.segmentation_settings_header.setFont(font)
        self.segmentation_settings_header.setObjectName("segmentation_settings_header")
        self.gridLayout_7.addWidget(self.segmentation_settings_header, 0, 0, 1, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.starting_image_label = QtWidgets.QLabel(self.centralwidget)
        self.starting_image_label.setObjectName("starting_image_label")
        self.gridLayout_6.addWidget(self.starting_image_label, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(28, 118, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 2, 1, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.starting_image = QtWidgets.QSpinBox(self.centralwidget)
        self.starting_image.setMaximum(9999)
        self.starting_image.setObjectName("starting_image")
        self.horizontalLayout_2.addWidget(self.starting_image)
        self.imaging_note_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imaging_note_label.sizePolicy().hasHeightForWidth())
        self.imaging_note_label.setSizePolicy(sizePolicy)
        self.imaging_note_label.setObjectName("imaging_note_label")
        self.horizontalLayout_2.addWidget(self.imaging_note_label)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.size_filter_label = QtWidgets.QLabel(self.centralwidget)
        self.size_filter_label.setObjectName("size_filter_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.size_filter_label)
        self.size_filter = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.size_filter.setDecimals(0)
        self.size_filter.setMaximum(1000.0)
        self.size_filter.setSingleStep(1.0)
        self.size_filter.setProperty("value", 50.0)
        self.size_filter.setObjectName("size_filter")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.size_filter)
        self.h_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h_label.sizePolicy().hasHeightForWidth())
        self.h_label.setSizePolicy(sizePolicy)
        self.h_label.setObjectName("h_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.h_label)
        self.h = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.h.setDecimals(5)
        self.h.setSingleStep(0.01)
        self.h.setProperty("value", 0.5)
        self.h.setObjectName("h")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.h)
        self.gridLayout_6.addLayout(self.formLayout, 3, 0, 1, 1)
        self.segmentation_method_group_box = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segmentation_method_group_box.sizePolicy().hasHeightForWidth())
        self.segmentation_method_group_box.setSizePolicy(sizePolicy)
        self.segmentation_method_group_box.setObjectName("segmentation_method_group_box")
        self.basic_radio_button = QtWidgets.QRadioButton(self.segmentation_method_group_box)
        self.basic_radio_button.setGeometry(QtCore.QRect(10, 15, 82, 21))
        self.basic_radio_button.setObjectName("basic_radio_button")
        self.watershed_radio_button = QtWidgets.QRadioButton(self.segmentation_method_group_box)
        self.watershed_radio_button.setGeometry(QtCore.QRect(10, 26, 82, 31))
        self.watershed_radio_button.setObjectName("watershed_radio_button")
        self.gridLayout_6.addWidget(self.segmentation_method_group_box, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.watershed_and_ellipse_fit_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.watershed_and_ellipse_fit_frame.sizePolicy().hasHeightForWidth())
        self.watershed_and_ellipse_fit_frame.setSizePolicy(sizePolicy)
        self.watershed_and_ellipse_fit_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.watershed_and_ellipse_fit_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.watershed_and_ellipse_fit_frame.setObjectName("watershed_and_ellipse_fit_frame")
        self.widget = QtWidgets.QWidget(self.watershed_and_ellipse_fit_frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 321, 141))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.segmented_layout = QtWidgets.QVBoxLayout()
        self.segmented_layout.setObjectName("segmented_layout")
        self.horizontalLayout_4.addLayout(self.segmented_layout)
        self.ellipse_fit_layout = QtWidgets.QVBoxLayout()
        self.ellipse_fit_layout.setObjectName("ellipse_fit_layout")
        self.horizontalLayout_4.addLayout(self.ellipse_fit_layout)
        self.gridLayout_7.addWidget(self.watershed_and_ellipse_fit_frame, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        spacerItem9 = QtWidgets.QSpacerItem(518, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.pause_interval_label = QtWidgets.QLabel(self.centralwidget)
        self.pause_interval_label.setObjectName("pause_interval_label")
        self.horizontalLayout.addWidget(self.pause_interval_label)
        self.pause_interval = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pause_interval.setDecimals(0)
        self.pause_interval.setMaximum(1000.0)
        self.pause_interval.setSingleStep(1.0)
        self.pause_interval.setProperty("value", 12.0)
        self.pause_interval.setObjectName("pause_interval")
        self.horizontalLayout.addWidget(self.pause_interval)
        self.move_on = QtWidgets.QCheckBox(self.centralwidget)
        self.move_on.setObjectName("move_on")
        self.horizontalLayout.addWidget(self.move_on)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pause_button.setFont(font)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout.addWidget(self.pause_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.plots_header = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plots_header.setFont(font)
        self.plots_header.setObjectName("plots_header")
        self.verticalLayout_6.addWidget(self.plots_header)
        self.plot_tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.plot_tabs.sizePolicy().hasHeightForWidth())
        self.plot_tabs.setSizePolicy(sizePolicy)
        self.plot_tabs.setObjectName("plot_tabs")
        self.radius_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radius_tab.sizePolicy().hasHeightForWidth())
        self.radius_tab.setSizePolicy(sizePolicy)
        self.radius_tab.setObjectName("radius_tab")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.radius_tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(-1, -1, 521, 261))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.radius_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.radius_layout.setContentsMargins(0, 0, 0, 0)
        self.radius_layout.setObjectName("radius_layout")
        self.plot_tabs.addTab(self.radius_tab, "")
        self.ratio_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratio_tab.sizePolicy().hasHeightForWidth())
        self.ratio_tab.setSizePolicy(sizePolicy)
        self.ratio_tab.setObjectName("ratio_tab")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.ratio_tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(-1, -1, 521, 261))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.ratio_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.ratio_layout.setContentsMargins(0, 0, 0, 0)
        self.ratio_layout.setObjectName("ratio_layout")
        self.plot_tabs.addTab(self.ratio_tab, "")
        self.angle_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_tab.sizePolicy().hasHeightForWidth())
        self.angle_tab.setSizePolicy(sizePolicy)
        self.angle_tab.setObjectName("angle_tab")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.angle_tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(-1, -1, 521, 261))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.angle_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.angle_layout.setContentsMargins(0, 0, 0, 0)
        self.angle_layout.setObjectName("angle_layout")
        self.plot_tabs.addTab(self.angle_tab, "")
        self.verticalLayout_6.addWidget(self.plot_tabs)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem11 = QtWidgets.QSpacerItem(11, 558, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.plot_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image_settings_header.setText(_translate("MainWindow", "Select images and enter settings:"))
        self.background_group_box.setTitle(_translate("MainWindow", "Background"))
        self.dark_radio_button.setText(_translate("MainWindow", "Dark"))
        self.light_radio_button.setText(_translate("MainWindow", "Light"))
        self.submit_settings_button.setText(_translate("MainWindow", "Submit Settings"))
        self.length_conversion_label.setText(_translate("MainWindow", "Length conversion:"))
        self.folder_label.setText(_translate("MainWindow", "Image Folder:"))
        self.imaging_time_units.setText(_translate("MainWindow", "hrs"))
        self.length_conversion_units.setText(_translate("MainWindow", "pix/mm"))
        self.imaging_time_label.setText(_translate("MainWindow", "Imaging time:"))
        self.image_folder_button.setText(_translate("MainWindow", "..."))
        self.save_folder_label.setText(_translate("MainWindow", "Save Folder:"))
        self.filename_label.setText(_translate("MainWindow", "Filename:"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.save_results_header.setText(_translate("MainWindow", "Save results:"))
        self.save_folder_button.setText(_translate("MainWindow", "..."))
        self.crop_settings_header.setText(_translate("MainWindow", "Set crop for first image:"))
        self.cropping_note_label.setText(_translate("MainWindow", "(Use sliders to select center of object)"))
        self.set_crop_button.setText(_translate("MainWindow", "Set Crop"))
        self.ideal_crop_label.setText(_translate("MainWindow", "Crop size:"))
        self.ideal_crop_units.setText(_translate("MainWindow", "pix"))
        self.segmentation_settings_header.setText(_translate("MainWindow", "Set segmentation:"))
        self.starting_image_label.setText(_translate("MainWindow", "Starting image:"))
        self.imaging_note_label.setText(_translate("MainWindow", "(First image is 0)"))
        self.size_filter_label.setText(_translate("MainWindow", "Size filter: "))
        self.h_label.setText(_translate("MainWindow", "h:"))
        self.segmentation_method_group_box.setTitle(_translate("MainWindow", "Segmentation method"))
        self.basic_radio_button.setText(_translate("MainWindow", "Basic"))
        self.watershed_radio_button.setText(_translate("MainWindow", "Watershed"))
        self.pause_interval_label.setText(_translate("MainWindow", "Pause interval:"))
        self.move_on.setText(_translate("MainWindow", "Move on to next section"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        self.plots_header.setText(_translate("MainWindow", "Plots:"))
        self.plot_tabs.setTabText(self.plot_tabs.indexOf(self.radius_tab), _translate("MainWindow", "Radius"))
        self.plot_tabs.setTabText(self.plot_tabs.indexOf(self.ratio_tab), _translate("MainWindow", "Aspect Ratio"))
        self.plot_tabs.setTabText(self.plot_tabs.indexOf(self.angle_tab), _translate("MainWindow", "Angle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

